service: serverless-sample
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
frameworkVersion: "3"

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x

functions:
  first:
    handler: first.hello
    events:
      - schedule: cron(0 * * * ? *)
  second:
    handler: second.hello
    events:
      - httpApi:
          method: get
          path: /second
  qiita:
    handler: qiita.hello
    environment:
      endpoint: https://qiita.com/api/v2/users/dev63/items
